# Wiki.js Configuration

port: 3000

db:
  type: postgres
  host: $$DB_HOST
  port: $$DB_PORT
  user: $$DB_USER
  pass: $$DB_PASS
  db: $$DB_NAME
  ssl: $$DB_SSL

bindIP: 0.0.0.0
logLevel: info

# Default administrator account
admin:
  email: admin@solarshrine.org

# Set to false since we're on Render's CDN
ssl:
  enabled: false

# The rest will use defaults 