services:
  - type: web
    name: solar-shrine-wiki
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        value: dpg-${RENDER_DATABASE_ID}-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        sync: false # You'll need to enter the password in the Render dashboard
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: true
      - key: WIKI_ADMIN_EMAIL
        value: admin@solarshrine.org # Change to your admin email
    domains:
      - wiki.solarshrine.org

databases:
  - name: solar-shrine-db
    plan: free
    region: oregon 