services:
  - type: web
    name: solar-shrine-wiki
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_URL
        fromDatabase:
          name: solar-shrine-db
          property: connectionString
      - key: WIKI_ADMIN_EMAIL
        value: admin@solarshrine.org
    domains:
      - wiki.solarshrine.org

databases:
  - name: solar-shrine-db
    plan: free
    region: oregon 