services:
  - type: web
    name: solar-shrine-wiki
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        value: db.ofnxuxemfvuwipeireuy.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        value: solarshrine2025
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: "true"
      - key: WIKI_ADMIN_EMAIL
        value: admin@solarshrine.org
    domains:
      - wiki.solarshrine.org

databases:
  - name: solar-shrine-db
    plan: free
    region: oregon 