services:
  - type: web
    name: solar-shrine-wiki
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        fromService:
          name: solar-shrine-db
          type: pserv
          property: host
      - key: DB_PORT
        fromService:
          name: solar-shrine-db
          type: pserv
          property: port
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        generateValue: true
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: false
      - key: WIKI_ADMIN_EMAIL
        value: admin@solarshrine.org # Change to your admin email
    domains:
      - wiki.solarshrine.org

  - type: pserv
    name: solar-shrine-db
    plan: free
    region: oregon
    databaseName: postgres
    user: postgres 