services:
  - type: web
    name: solar-shrine-wiki
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/requarks/wiki-heroku
    branch: 2.x
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: solar-shrine-db
          property: connectionString
      - key: PORT
        value: "3000"
      - key: WIKI_ADMIN_EMAIL
        value: admin@solarshrine.org
    domains:
      - wiki.solarshrine.org

databases:
  - name: solar-shrine-db
    plan: free
    region: oregon 