services:
  - type: web
    name: solar-shrine-wiki
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /healthz
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: "true"
      - key: DB_HOST
        fromService:
          type: postgres
          name: solar-shrine-db
          property: host
      - key: DB_PORT
        fromService:
          type: postgres
          name: solar-shrine-db
          property: port
      - key: DB_PASS
        fromService:
          type: postgres
          name: solar-shrine-db
          property: password
      - key: WIKI_ADMIN_EMAIL
        value: admin@solarshrine.org
    domains:
      - wiki.solarshrine.org

  - type: postgres
    name: solar-shrine-db
    plan: free
    region: oregon
    ipAllowList: [] # only allow internal connections 