services:
  - type: web
    name: solar-shrine-wiki
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: solar-shrine-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: solar-shrine-db
          property: port
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        fromDatabase:
          name: solar-shrine-db
          property: password
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: false
      - key: WIKI_ADMIN_EMAIL
        value: admin@solarshrine.org # Change to your admin email
    domains:
      - wiki.solarshrine.org

databases:
  - name: solar-shrine-db
    plan: free
    region: oregon 